// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communication.proto

package communication

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender               string   `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipients           []string `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Subject              string   `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{0}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SendEmailRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SendEmailRequest) GetRecipients() []string {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *SendEmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendEmailRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendEmailReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailReply) Reset()         { *m = SendEmailReply{} }
func (m *SendEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendEmailReply) ProtoMessage()    {}
func (*SendEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{1}
}

func (m *SendEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailReply.Unmarshal(m, b)
}
func (m *SendEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailReply.Marshal(b, m, deterministic)
}
func (m *SendEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailReply.Merge(m, src)
}
func (m *SendEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendEmailReply.Size(m)
}
func (m *SendEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailReply proto.InternalMessageInfo

func (m *SendEmailReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type SendStatusRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStatusRequest) Reset()         { *m = SendStatusRequest{} }
func (m *SendStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SendStatusRequest) ProtoMessage()    {}
func (*SendStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{2}
}

func (m *SendStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStatusRequest.Unmarshal(m, b)
}
func (m *SendStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStatusRequest.Marshal(b, m, deterministic)
}
func (m *SendStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStatusRequest.Merge(m, src)
}
func (m *SendStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SendStatusRequest.Size(m)
}
func (m *SendStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendStatusRequest proto.InternalMessageInfo

func (m *SendStatusRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SendStatusRequest) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SendStatusReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStatusReply) Reset()         { *m = SendStatusReply{} }
func (m *SendStatusReply) String() string { return proto.CompactTextString(m) }
func (*SendStatusReply) ProtoMessage()    {}
func (*SendStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{3}
}

func (m *SendStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStatusReply.Unmarshal(m, b)
}
func (m *SendStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStatusReply.Marshal(b, m, deterministic)
}
func (m *SendStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStatusReply.Merge(m, src)
}
func (m *SendStatusReply) XXX_Size() int {
	return xxx_messageInfo_SendStatusReply.Size(m)
}
func (m *SendStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendStatusReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendEmailRequest)(nil), "SendEmailRequest")
	proto.RegisterType((*SendEmailReply)(nil), "SendEmailReply")
	proto.RegisterType((*SendStatusRequest)(nil), "SendStatusRequest")
	proto.RegisterType((*SendStatusReply)(nil), "SendStatusReply")
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor_b64068f22c460ac1) }

var fileDescriptor_b64068f22c460ac1 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x9b, 0x06, 0x02, 0xb9, 0xa1, 0x6d, 0x8c, 0x84, 0xac, 0x0e, 0x28, 0xf2, 0x94, 0xc9,
	0x12, 0x85, 0x0d, 0x31, 0x74, 0x60, 0x60, 0x40, 0x42, 0xee, 0x13, 0xb8, 0xce, 0x09, 0x19, 0x25,
	0x4e, 0xc8, 0x39, 0x43, 0x5f, 0x82, 0x67, 0x46, 0x71, 0x5b, 0x08, 0x45, 0x8c, 0x9f, 0xcf, 0xbf,
	0xff, 0x4f, 0x3e, 0xb8, 0x32, 0x4d, 0x5d, 0xf7, 0xce, 0x1a, 0xed, 0x6d, 0xe3, 0x64, 0xdb, 0x35,
	0xbe, 0x11, 0x9f, 0x11, 0x2c, 0x36, 0xe8, 0xca, 0xa7, 0x5a, 0xdb, 0x4a, 0xe1, 0x47, 0x8f, 0xe4,
	0xd9, 0x0c, 0xa6, 0xb6, 0xe4, 0x51, 0x1e, 0x15, 0xb1, 0x9a, 0xda, 0x92, 0x5d, 0x43, 0x42, 0xe8,
	0x4a, 0xec, 0xf8, 0x34, 0x8f, 0x8a, 0x54, 0x1d, 0x88, 0xdd, 0x00, 0x74, 0x68, 0x6c, 0x6b, 0xd1,
	0x79, 0xe2, 0x71, 0x1e, 0x17, 0xa9, 0x1a, 0x9d, 0x30, 0x0e, 0x17, 0xd4, 0x6f, 0xdf, 0xd1, 0x78,
	0x7e, 0x16, 0x82, 0x47, 0x1c, 0x26, 0x35, 0x12, 0xe9, 0x37, 0xe4, 0xe7, 0xfb, 0xc9, 0x01, 0x45,
	0x01, 0xb3, 0x91, 0x4f, 0x5b, 0xed, 0x42, 0xbb, 0xd7, 0xbe, 0xa7, 0x60, 0x34, 0xb4, 0x07, 0x12,
	0x8f, 0x90, 0x0d, 0x37, 0x37, 0x81, 0xfe, 0x53, 0x0f, 0x0a, 0xc6, 0x20, 0x51, 0x70, 0xbf, 0x54,
	0x47, 0x14, 0x19, 0xcc, 0xc7, 0xf1, 0xb6, 0xda, 0xad, 0x1e, 0x20, 0x79, 0xd1, 0xb6, 0xc2, 0x8e,
	0xdd, 0x42, 0xfa, 0x6d, 0xc1, 0x32, 0x79, 0xfa, 0x43, 0xcb, 0xb9, 0xfc, 0x2d, 0x29, 0x26, 0xab,
	0x35, 0xa4, 0xfb, 0xf0, 0xfa, 0xf5, 0x99, 0xdd, 0x03, 0xfc, 0x3c, 0xce, 0x98, 0xfc, 0x23, 0xba,
	0x5c, 0xc8, 0x93, 0x76, 0x31, 0xd9, 0x26, 0x61, 0x27, 0x77, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x02, 0x41, 0x31, 0xd0, 0xaa, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailerClient is the client API for Mailer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailerClient interface {
	// Sends an email
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error)
}

type mailerClient struct {
	cc *grpc.ClientConn
}

func NewMailerClient(cc *grpc.ClientConn) MailerClient {
	return &mailerClient{cc}
}

func (c *mailerClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error) {
	out := new(SendEmailReply)
	err := c.cc.Invoke(ctx, "/Mailer/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailerServer is the server API for Mailer service.
type MailerServer interface {
	// Sends an email
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailReply, error)
}

// UnimplementedMailerServer can be embedded to have forward compatible implementations.
type UnimplementedMailerServer struct {
}

func (*UnimplementedMailerServer) SendEmail(ctx context.Context, req *SendEmailRequest) (*SendEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}

func RegisterMailerServer(s *grpc.Server, srv MailerServer) {
	s.RegisterService(&_Mailer_serviceDesc, srv)
}

func _Mailer_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mailer/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mailer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Mailer",
	HandlerType: (*MailerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Mailer_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}

// MailerAPIClient is the client API for MailerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailerAPIClient interface {
	SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusReply, error)
}

type mailerAPIClient struct {
	cc *grpc.ClientConn
}

func NewMailerAPIClient(cc *grpc.ClientConn) MailerAPIClient {
	return &mailerAPIClient{cc}
}

func (c *mailerAPIClient) SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusReply, error) {
	out := new(SendStatusReply)
	err := c.cc.Invoke(ctx, "/MailerAPI/SendStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailerAPIServer is the server API for MailerAPI service.
type MailerAPIServer interface {
	SendStatus(context.Context, *SendStatusRequest) (*SendStatusReply, error)
}

// UnimplementedMailerAPIServer can be embedded to have forward compatible implementations.
type UnimplementedMailerAPIServer struct {
}

func (*UnimplementedMailerAPIServer) SendStatus(ctx context.Context, req *SendStatusRequest) (*SendStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStatus not implemented")
}

func RegisterMailerAPIServer(s *grpc.Server, srv MailerAPIServer) {
	s.RegisterService(&_MailerAPI_serviceDesc, srv)
}

func _MailerAPI_SendStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerAPIServer).SendStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MailerAPI/SendStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerAPIServer).SendStatus(ctx, req.(*SendStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailerAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MailerAPI",
	HandlerType: (*MailerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendStatus",
			Handler:    _MailerAPI_SendStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}
