---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hes-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hes-api
    spec:
      containers:
        - name: hes-api
          image: ros3n/hes-api:latest # for the sake of simplicity
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
          envFrom:
            - secretRef:
                name: hes-secrets
