---
kind: Service
apiVersion: v1
metadata:
  name: hes-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hes-api

---
kind: Service
apiVersion: v1
metadata:
  name: hes-api-internal
spec:
  selector:
    app: hes-api
  ports:
    - protocol: TCP
      port: 5555
